# Generated by Django 5.1.2 on 2024-12-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='owner',
            unique_together={('first_name', 'last_name')},
        ),
    ]
